version: "3.8"

services:
  app:
    build: .
    container_name: php-userauth-example-app
    ports:
      - "8080:80"
    volumes:
      - ./php-userauth-example:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_DATABASE=php-userauth-example
      - DB_USERNAME=php-userauth-example
      - DB_PASSWORD=php-userauth-example
  db:
    image: arm64v8/mysql:8
    container_name: php-userauth-example-db
    ports:
      - "3307:3307"
    volumes:
      - php-userauth-example-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=php-userauth-example
      - MYSQL_DATABASE=php-userauth-example
      - MYSQL_USER=php-userauth-example
      - MYSQL_PASSWORD=php-userauth-example
      - MYSQL_TCP_PORT=3307

  kvs:
    image: redis:latest
    container_name: php-userauth-example-kvs
    ports:
      - "6379:6379"
    volumes:
      - php-userauth-example-kvs-data:/data


volumes:
  php-userauth-example-db-data:
  php-userauth-example-kvs-data:
